version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    artifact1:
      files:
        - '**/*'
      base-directory: dist
      name: app
      discard-paths: no