version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync arn:aws:s3:::volodka-trello-ui/
artifacts:
  files:
    - '**/*'